
# Cria uma nova matricula
POST http://localhost:8080/registrations/new
Content-Type: application/json

{
  "studentCode": "CODE0.5493706117836301",
  "subjectCode": "S001",
  "classCode": 1
}

###

# Busca todos os estudantes cadastrados
GET http://localhost:8080/students

###

# Registra um novo estudante
POST http://localhost:8080/students/create
Content-Type: application/json

{
  "name": "Matheus Santos dos Santos",
  "rg": "000.000.000-00",
  "address": {
    "street": "Nome da rua",
	  "number": "888",
	  "complement": "Casa 1",
	  "zipcode": "000000-00"
  }
}

###

# Registra uma nova disciplina
POST http://localhost:8080/subjects/create
Content-Type: application/json

{
  "code": "S001",
  "name": "FDS",
  "turn": "A",
  "classCode": 1
}

###

# Busca todas as disciplinas
GET http://localhost:8080/subjects

###

# Busca todas as matriculas
GET http://localhost:8080/registrations

###

# Busca as disciplinas em que um estudante está matriculado
GET http://localhost:8080/registrations/student/CODE0.211747224131597045

###

# Busca todos os estudantes matriculados em uma disciplina
GET http://localhost:8080/subjects/S001/students

